### PR TITLE
Manual osx-arm64 migration

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
This is ready for review @a-hurst @dschreij

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin  please rerender

**Comment by Tobias-Fischer** [comment]
Now it’s really ready :)

**Comment by Tobias-Fischer** [comment]
Kind reminder @dschreij @a-hurst

**Comment by Tobias-Fischer** [comment]
Hi @conda-forge/help-osx-arm64  any chance you could merge here please? The maintainers seem unresponsive. I’ve got no interest in maintaining the feedstock.

**Review by xhochy — APPROVED** [review]

**Comment by Tobias-Fischer** [comment]
Thank you :)

**Pull request merged**
